### ISSUE TITLE
Make the full API accessible via the CLI

### ISSUE THREAD

**Issue by advance512** [TehShrike/glob-module-file#1]
Instead of a simple glob, add support for a regexp.
Or, an exclusion lists: e.g. *.test.js and *.storyboard.js

Nice tool! Thank you.

**Comment by TehShrike** [comment]
`glob` does support exclusions, via the `ignore` [option](https://www.npmjs.com/package/glob#options)!

One of the reasons to roll with the glob module is because it's so widely used and does so much at this point, it seems like it probably covers most use cases people have in the "identify a bunch of files" problem space.

And thanks, I hope this tool works well for people! :-)

**Comment by advance512** [comment]
Oh. I was using it as a CLI tool. :)
I want to trigger it as part of a Yeoman generator, and create "optimized" indexes of directories. I guess I can do it programatically too :)
Thanks!

**Comment by TehShrike** [comment]
Oh, yeah.  Yeah, the CLI options really suck right now.  I need to add [`minimist`](https://www.npmjs.com/package/minimist) or something and make it possible to pass the module+glob options in.

Pull requests welcome, otherwise I'll probably get to this in the next few days.

**Comment by TehShrike** [comment]
Published as 2.0.0.

**Comment by TehShrike** [comment]
Let me know if the current CLI works for you @advance512!

**Comment by advance512** [comment]
Great, will look soon! 👍
